# GET https://api.mapbox.com/geocoding/v5/mapbox.places/London/gym.json?access_token=token
# Content-Type: application/json

# GET https://api.mapbox.com/search/searchbox/v1/suggest?q=gym&language=en&limit=10&country=gb&access_token=token

# GET https://api.mapbox.com/search/searchbox/v1/category/coffee?access_token=token&language=en&limit=5&proximity=-73.935242%2C40

GET https://api.postcodes.io/postcodes/e149jw
Content-Type: application/json



